version: 2.1
orbs:
  codecov: codecov/codecov@4.0.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Run tests1
          command: mvn test
      - codecov/upload
      - save_cache:
          key: v1-dependencies-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2

workflows:
  version: 2
  build:
    jobs:
      - test-java:
          filters:
            branches:
              only:
                - master
  upload-to-codecov:
    jobs:
      - codecov/upload:
          token: be05f913-1062-47e9-9166-abe5172bbe7c
