version: 2.1

jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Run tests
          command: mvn test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: abdelouahedKanouni/ceri-m1-techniques-de-test
      - save_cache:
          key: v1-dependencies-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2

workflows:
  version: 2
  build:
    jobs:
      - test-java:
          filters:
            branches:
              only:
                - master
