version: 2.1


orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-ea-buster-node-browsers-legacy

    steps:
      - checkout  # Récupère le code source du dépôt

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test -X
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: install1
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: install2
          command: sudo apt-get update
      - run:
          name: install3
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Build-docs
          command: javadoc src/main/java/fr/univavignon/pokedex/api/* -d docs
      - persist_to_workspace:
          root: .
          paths: docs
    docs-deploy:
      docker:
        - image: node:8.10.0
      steps:
        - checkout
        - attach_workspace:
            at: docs/
        - run:
            name: Install and configure dependencies
            command: |
              npm install -g --silent gh-pages@2.0.1
              git config user.email "abdelouahed.kanouni@alumni.univ-avignon.fr"
        - add_ssh_keys:
            fingerprints:
              - "1cpd+vkCBiGTwZnsoOXWthKp02zoYfVt4nc6sA+NEWQ"
        - run:
            name: Deploy docs to gh-pages branch
            command: gh-pages --dist docs/

workflows: # Définition des workflows
  version: 2
  upload-to-codecov:
    jobs:
      - build
  maven_test:
    jobs:
      - docs-deploy:
            requires:
              - build-and-test
      - build:
          filters:
            branches:
              only: master